import { ModelInit, MutableModel, PersistentModelConstructor } from "@aws-amplify/datastore";





type BfaMetaData = {
  readOnlyFields: 'createdAt' | 'updatedAt';
}

export declare class Bfa {
  readonly id: string;
  readonly height?: string;
  readonly weight?: string;
  readonly restingbp?: string;
  readonly restinghr?: string;
  readonly maxhr?: string;
  readonly recoveryhr?: string;
  readonly fitnesscategory?: string;
  readonly pelvisleft?: string;
  readonly pelvisright?: string;
  readonly kneepositionleft?: string;
  readonly kneepositionright?: string;
  readonly trunkpositionleft?: string;
  readonly trunkpositionright?: string;
  readonly steadystanceleft?: string;
  readonly steadystanceright?: string;
  readonly armstrategyleft?: string;
  readonly armstrategyright?: string;
  readonly scoliosisadams?: string;
  readonly ribhump?: string;
  readonly ribarea?: string;
  readonly fordwardbending?: string;
  readonly knees?: string;
  readonly genurecurvatumleft?: string;
  readonly scapularwingingleft?: string;
  readonly footalignmentleft?: string;
  readonly halluxvalgusleft?: string;
  readonly genurecurvatumright?: string;
  readonly scapularwingingright?: string;
  readonly footalignmentright?: string;
  readonly halluxvalgusright?: string;
  readonly goodalignment?: string;
  readonly valgusvarus?: string;
  readonly range?: string;
  readonly sufficientupwardrotationleft?: string;
  readonly jitteringleft?: string;
  readonly wingingleft?: string;
  readonly sufficientupwardrotationright?: string;
  readonly jitteringright?: string;
  readonly wingingright?: string;
  readonly passivedfleft?: string;
  readonly passivedfright?: string;
  readonly passiveappleft?: string;
  readonly passiveappright?: string;
  readonly hyperextensionelbowleft?: string;
  readonly hyperextensionelbowright?: string;
  readonly firststpostitionturnoutleft?: string;
  readonly firststpostitionturnoutright?: string;
  readonly firstpositiondiscsleft?: string;
  readonly firstpositiondiscsright?: string;
  readonly thomastestleft?: string;
  readonly thomastestright?: string;
  readonly hipgrindleft?: string;
  readonly hipgrindright?: string;
  readonly slrhsleft?: string;
  readonly slrhsright?: string;
  readonly kneehyperextensionleft?: string;
  readonly kneehyperextensionright?: string;
  readonly pronehipirleft?: string;
  readonly pronehipirright?: string;
  readonly pronehiperleft?: string;
  readonly pronehiperright?: string;
  readonly plantarflexionaromleft?: string;
  readonly plantarflexionaromright?: string;
  readonly firststmtpdorsiflexionleft?: string;
  readonly firststmtpdorsiflexionright?: string;
  readonly leglength?: string;
  readonly hipabductionleft?: string;
  readonly hipabductionright?: string;
  readonly hipadductionleft?: string;
  readonly hipadductionright?: string;
  readonly hiperleft?: string;
  readonly hiperright?: string;
  readonly kneeflexionleft?: string;
  readonly kneeflexionright?: string;
  readonly hipabductionleft2?: string;
  readonly hipabductionright2?: string;
  readonly hipadductionleft2?: string;
  readonly hipadductionright2?: string;
  readonly hiperleft2?: string;
  readonly hiperright2?: string;
  readonly kneeflexionleft2?: string;
  readonly kneeflexionright2?: string;
  readonly singlelegstanceleft?: string;
  readonly singlelegstanceright?: string;
  readonly anteriorleft1?: string;
  readonly anteriorleft2?: string;
  readonly anteriorleft3?: string;
  readonly anteriorright1?: string;
  readonly anteriorright2?: string;
  readonly anteriorright3?: string;
  readonly posteromedialleft1?: string;
  readonly posteromedialleft2?: string;
  readonly posteromedialleft3?: string;
  readonly posteromedialright1?: string;
  readonly posteromedialright2?: string;
  readonly posteromedialright3?: string;
  readonly posterolateralleft1?: string;
  readonly posterolateralleft2?: string;
  readonly posterolateralleft3?: string;
  readonly posterolateralright1?: string;
  readonly posterolateralright2?: string;
  readonly posterolateralright3?: string;
  readonly singlelegreleveleft?: string;
  readonly singlelegreleveright?: string;
  readonly singlelegbridgeleft?: string;
  readonly singlelegbridgeright?: string;
  readonly sideplankhipableft?: string;
  readonly sideplankhipabright?: string;
  readonly powerhoptestleft?: string;
  readonly powerhoptestright?: string;
  readonly ckcuest?: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  constructor(init: ModelInit<Bfa, BfaMetaData>);
  static copyOf(source: Bfa, mutator: (draft: MutableModel<Bfa, BfaMetaData>) => MutableModel<Bfa, BfaMetaData> | void): Bfa;
}