/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const getBfa = /* GraphQL */ `
  query GetBfa($id: ID!) {
    getBfa(id: $id) {
      id
      height
      weight
      restingbp
      restinghr
      maxhr
      recoveryhr
      fitnesscategory
      pelvisleft
      pelvisright
      kneepositionleft
      kneepositionright
      trunkpositionleft
      trunkpositionright
      steadystanceleft
      steadystanceright
      armstrategyleft
      armstrategyright
      scoliosisadams
      ribhump
      ribarea
      fordwardbending
      knees
      genurecurvatumleft
      scapularwingingleft
      footalignmentleft
      halluxvalgusleft
      genurecurvatumright
      scapularwingingright
      footalignmentright
      halluxvalgusright
      goodalignment
      valgusvarus
      range
      sufficientupwardrotationleft
      jitteringleft
      wingingleft
      sufficientupwardrotationright
      jitteringright
      wingingright
      passivedfleft
      passivedfright
      passiveappleft
      passiveappright
      hyperextensionelbowleft
      hyperextensionelbowright
      firststpostitionturnoutleft
      firststpostitionturnoutright
      firstpositiondiscsleft
      firstpositiondiscsright
      thomastestleft
      thomastestright
      hipgrindleft
      hipgrindright
      slrhsleft
      slrhsright
      kneehyperextensionleft
      kneehyperextensionright
      pronehipirleft
      pronehipirright
      pronehiperleft
      pronehiperright
      plantarflexionaromleft
      plantarflexionaromright
      firststmtpdorsiflexionleft
      firststmtpdorsiflexionright
      leglength
      hipabductionleft
      hipabductionright
      hipadductionleft
      hipadductionright
      hiperleft
      hiperright
      kneeflexionleft
      kneeflexionright
      hipabductionleft2
      hipabductionright2
      hipadductionleft2
      hipadductionright2
      hiperleft2
      hiperright2
      kneeflexionleft2
      kneeflexionright2
      singlelegstanceleft
      singlelegstanceright
      anteriorleft1
      anteriorleft2
      anteriorleft3
      anteriorright1
      anteriorright2
      anteriorright3
      posteromedialleft1
      posteromedialleft2
      posteromedialleft3
      posteromedialright1
      posteromedialright2
      posteromedialright3
      posterolateralleft1
      posterolateralleft2
      posterolateralleft3
      posterolateralright1
      posterolateralright2
      posterolateralright3
      singlelegreleveleft
      singlelegreleveright
      singlelegbridgeleft
      singlelegbridgeright
      sideplankhipableft
      sideplankhipabright
      powerhoptestleft
      powerhoptestright
      ckcuest
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const listBfas = /* GraphQL */ `
  query ListBfas(
    $filter: ModelBfaFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listBfas(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        height
        weight
        restingbp
        restinghr
        maxhr
        recoveryhr
        fitnesscategory
        pelvisleft
        pelvisright
        kneepositionleft
        kneepositionright
        trunkpositionleft
        trunkpositionright
        steadystanceleft
        steadystanceright
        armstrategyleft
        armstrategyright
        scoliosisadams
        ribhump
        ribarea
        fordwardbending
        knees
        genurecurvatumleft
        scapularwingingleft
        footalignmentleft
        halluxvalgusleft
        genurecurvatumright
        scapularwingingright
        footalignmentright
        halluxvalgusright
        goodalignment
        valgusvarus
        range
        sufficientupwardrotationleft
        jitteringleft
        wingingleft
        sufficientupwardrotationright
        jitteringright
        wingingright
        passivedfleft
        passivedfright
        passiveappleft
        passiveappright
        hyperextensionelbowleft
        hyperextensionelbowright
        firststpostitionturnoutleft
        firststpostitionturnoutright
        firstpositiondiscsleft
        firstpositiondiscsright
        thomastestleft
        thomastestright
        hipgrindleft
        hipgrindright
        slrhsleft
        slrhsright
        kneehyperextensionleft
        kneehyperextensionright
        pronehipirleft
        pronehipirright
        pronehiperleft
        pronehiperright
        plantarflexionaromleft
        plantarflexionaromright
        firststmtpdorsiflexionleft
        firststmtpdorsiflexionright
        leglength
        hipabductionleft
        hipabductionright
        hipadductionleft
        hipadductionright
        hiperleft
        hiperright
        kneeflexionleft
        kneeflexionright
        hipabductionleft2
        hipabductionright2
        hipadductionleft2
        hipadductionright2
        hiperleft2
        hiperright2
        kneeflexionleft2
        kneeflexionright2
        singlelegstanceleft
        singlelegstanceright
        anteriorleft1
        anteriorleft2
        anteriorleft3
        anteriorright1
        anteriorright2
        anteriorright3
        posteromedialleft1
        posteromedialleft2
        posteromedialleft3
        posteromedialright1
        posteromedialright2
        posteromedialright3
        posterolateralleft1
        posterolateralleft2
        posterolateralleft3
        posterolateralright1
        posterolateralright2
        posterolateralright3
        singlelegreleveleft
        singlelegreleveright
        singlelegbridgeleft
        singlelegbridgeright
        sideplankhipableft
        sideplankhipabright
        powerhoptestleft
        powerhoptestright
        ckcuest
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
      }
      nextToken
      startedAt
    }
  }
`;
export const syncBfas = /* GraphQL */ `
  query SyncBfas(
    $filter: ModelBfaFilterInput
    $limit: Int
    $nextToken: String
    $lastSync: AWSTimestamp
  ) {
    syncBfas(
      filter: $filter
      limit: $limit
      nextToken: $nextToken
      lastSync: $lastSync
    ) {
      items {
        id
        height
        weight
        restingbp
        restinghr
        maxhr
        recoveryhr
        fitnesscategory
        pelvisleft
        pelvisright
        kneepositionleft
        kneepositionright
        trunkpositionleft
        trunkpositionright
        steadystanceleft
        steadystanceright
        armstrategyleft
        armstrategyright
        scoliosisadams
        ribhump
        ribarea
        fordwardbending
        knees
        genurecurvatumleft
        scapularwingingleft
        footalignmentleft
        halluxvalgusleft
        genurecurvatumright
        scapularwingingright
        footalignmentright
        halluxvalgusright
        goodalignment
        valgusvarus
        range
        sufficientupwardrotationleft
        jitteringleft
        wingingleft
        sufficientupwardrotationright
        jitteringright
        wingingright
        passivedfleft
        passivedfright
        passiveappleft
        passiveappright
        hyperextensionelbowleft
        hyperextensionelbowright
        firststpostitionturnoutleft
        firststpostitionturnoutright
        firstpositiondiscsleft
        firstpositiondiscsright
        thomastestleft
        thomastestright
        hipgrindleft
        hipgrindright
        slrhsleft
        slrhsright
        kneehyperextensionleft
        kneehyperextensionright
        pronehipirleft
        pronehipirright
        pronehiperleft
        pronehiperright
        plantarflexionaromleft
        plantarflexionaromright
        firststmtpdorsiflexionleft
        firststmtpdorsiflexionright
        leglength
        hipabductionleft
        hipabductionright
        hipadductionleft
        hipadductionright
        hiperleft
        hiperright
        kneeflexionleft
        kneeflexionright
        hipabductionleft2
        hipabductionright2
        hipadductionleft2
        hipadductionright2
        hiperleft2
        hiperright2
        kneeflexionleft2
        kneeflexionright2
        singlelegstanceleft
        singlelegstanceright
        anteriorleft1
        anteriorleft2
        anteriorleft3
        anteriorright1
        anteriorright2
        anteriorright3
        posteromedialleft1
        posteromedialleft2
        posteromedialleft3
        posteromedialright1
        posteromedialright2
        posteromedialright3
        posterolateralleft1
        posterolateralleft2
        posterolateralleft3
        posterolateralright1
        posterolateralright2
        posterolateralright3
        singlelegreleveleft
        singlelegreleveright
        singlelegbridgeleft
        singlelegbridgeright
        sideplankhipableft
        sideplankhipabright
        powerhoptestleft
        powerhoptestright
        ckcuest
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
      }
      nextToken
      startedAt
    }
  }
`;
