/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateBfa = /* GraphQL */ `
  subscription OnCreateBfa {
    onCreateBfa {
      id
      height
      weight
      restingbp
      restinghr
      maxhr
      recoveryhr
      fitnesscategory
      pelvisleft
      pelvisright
      kneepositionleft
      kneepositionright
      trunkpositionleft
      trunkpositionright
      steadystanceleft
      steadystanceright
      armstrategyleft
      armstrategyright
      scoliosisadams
      ribhump
      ribarea
      fordwardbending
      knees
      genurecurvatumleft
      scapularwingingleft
      footalignmentleft
      halluxvalgusleft
      genurecurvatumright
      scapularwingingright
      footalignmentright
      halluxvalgusright
      goodalignment
      valgusvarus
      range
      sufficientupwardrotationleft
      jitteringleft
      wingingleft
      sufficientupwardrotationright
      jitteringright
      wingingright
      passivedfleft
      passivedfright
      passiveappleft
      passiveappright
      hyperextensionelbowleft
      hyperextensionelbowright
      firststpostitionturnoutleft
      firststpostitionturnoutright
      firstpositiondiscsleft
      firstpositiondiscsright
      thomastestleft
      thomastestright
      hipgrindleft
      hipgrindright
      slrhsleft
      slrhsright
      kneehyperextensionleft
      kneehyperextensionright
      pronehipirleft
      pronehipirright
      pronehiperleft
      pronehiperright
      plantarflexionaromleft
      plantarflexionaromright
      firststmtpdorsiflexionleft
      firststmtpdorsiflexionright
      leglength
      hipabductionleft
      hipabductionright
      hipadductionleft
      hipadductionright
      hiperleft
      hiperright
      kneeflexionleft
      kneeflexionright
      hipabductionleft2
      hipabductionright2
      hipadductionleft2
      hipadductionright2
      hiperleft2
      hiperright2
      kneeflexionleft2
      kneeflexionright2
      singlelegstanceleft
      singlelegstanceright
      anteriorleft1
      anteriorleft2
      anteriorleft3
      anteriorright1
      anteriorright2
      anteriorright3
      posteromedialleft1
      posteromedialleft2
      posteromedialleft3
      posteromedialright1
      posteromedialright2
      posteromedialright3
      posterolateralleft1
      posterolateralleft2
      posterolateralleft3
      posterolateralright1
      posterolateralright2
      posterolateralright3
      singlelegreleveleft
      singlelegreleveright
      singlelegbridgeleft
      singlelegbridgeright
      sideplankhipableft
      sideplankhipabright
      powerhoptestleft
      powerhoptestright
      ckcuest
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateBfa = /* GraphQL */ `
  subscription OnUpdateBfa {
    onUpdateBfa {
      id
      height
      weight
      restingbp
      restinghr
      maxhr
      recoveryhr
      fitnesscategory
      pelvisleft
      pelvisright
      kneepositionleft
      kneepositionright
      trunkpositionleft
      trunkpositionright
      steadystanceleft
      steadystanceright
      armstrategyleft
      armstrategyright
      scoliosisadams
      ribhump
      ribarea
      fordwardbending
      knees
      genurecurvatumleft
      scapularwingingleft
      footalignmentleft
      halluxvalgusleft
      genurecurvatumright
      scapularwingingright
      footalignmentright
      halluxvalgusright
      goodalignment
      valgusvarus
      range
      sufficientupwardrotationleft
      jitteringleft
      wingingleft
      sufficientupwardrotationright
      jitteringright
      wingingright
      passivedfleft
      passivedfright
      passiveappleft
      passiveappright
      hyperextensionelbowleft
      hyperextensionelbowright
      firststpostitionturnoutleft
      firststpostitionturnoutright
      firstpositiondiscsleft
      firstpositiondiscsright
      thomastestleft
      thomastestright
      hipgrindleft
      hipgrindright
      slrhsleft
      slrhsright
      kneehyperextensionleft
      kneehyperextensionright
      pronehipirleft
      pronehipirright
      pronehiperleft
      pronehiperright
      plantarflexionaromleft
      plantarflexionaromright
      firststmtpdorsiflexionleft
      firststmtpdorsiflexionright
      leglength
      hipabductionleft
      hipabductionright
      hipadductionleft
      hipadductionright
      hiperleft
      hiperright
      kneeflexionleft
      kneeflexionright
      hipabductionleft2
      hipabductionright2
      hipadductionleft2
      hipadductionright2
      hiperleft2
      hiperright2
      kneeflexionleft2
      kneeflexionright2
      singlelegstanceleft
      singlelegstanceright
      anteriorleft1
      anteriorleft2
      anteriorleft3
      anteriorright1
      anteriorright2
      anteriorright3
      posteromedialleft1
      posteromedialleft2
      posteromedialleft3
      posteromedialright1
      posteromedialright2
      posteromedialright3
      posterolateralleft1
      posterolateralleft2
      posterolateralleft3
      posterolateralright1
      posterolateralright2
      posterolateralright3
      singlelegreleveleft
      singlelegreleveright
      singlelegbridgeleft
      singlelegbridgeright
      sideplankhipableft
      sideplankhipabright
      powerhoptestleft
      powerhoptestright
      ckcuest
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteBfa = /* GraphQL */ `
  subscription OnDeleteBfa {
    onDeleteBfa {
      id
      height
      weight
      restingbp
      restinghr
      maxhr
      recoveryhr
      fitnesscategory
      pelvisleft
      pelvisright
      kneepositionleft
      kneepositionright
      trunkpositionleft
      trunkpositionright
      steadystanceleft
      steadystanceright
      armstrategyleft
      armstrategyright
      scoliosisadams
      ribhump
      ribarea
      fordwardbending
      knees
      genurecurvatumleft
      scapularwingingleft
      footalignmentleft
      halluxvalgusleft
      genurecurvatumright
      scapularwingingright
      footalignmentright
      halluxvalgusright
      goodalignment
      valgusvarus
      range
      sufficientupwardrotationleft
      jitteringleft
      wingingleft
      sufficientupwardrotationright
      jitteringright
      wingingright
      passivedfleft
      passivedfright
      passiveappleft
      passiveappright
      hyperextensionelbowleft
      hyperextensionelbowright
      firststpostitionturnoutleft
      firststpostitionturnoutright
      firstpositiondiscsleft
      firstpositiondiscsright
      thomastestleft
      thomastestright
      hipgrindleft
      hipgrindright
      slrhsleft
      slrhsright
      kneehyperextensionleft
      kneehyperextensionright
      pronehipirleft
      pronehipirright
      pronehiperleft
      pronehiperright
      plantarflexionaromleft
      plantarflexionaromright
      firststmtpdorsiflexionleft
      firststmtpdorsiflexionright
      leglength
      hipabductionleft
      hipabductionright
      hipadductionleft
      hipadductionright
      hiperleft
      hiperright
      kneeflexionleft
      kneeflexionright
      hipabductionleft2
      hipabductionright2
      hipadductionleft2
      hipadductionright2
      hiperleft2
      hiperright2
      kneeflexionleft2
      kneeflexionright2
      singlelegstanceleft
      singlelegstanceright
      anteriorleft1
      anteriorleft2
      anteriorleft3
      anteriorright1
      anteriorright2
      anteriorright3
      posteromedialleft1
      posteromedialleft2
      posteromedialleft3
      posteromedialright1
      posteromedialright2
      posteromedialright3
      posterolateralleft1
      posterolateralleft2
      posterolateralleft3
      posterolateralright1
      posterolateralright2
      posterolateralright3
      singlelegreleveleft
      singlelegreleveright
      singlelegbridgeleft
      singlelegbridgeright
      sideplankhipableft
      sideplankhipabright
      powerhoptestleft
      powerhoptestright
      ckcuest
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
